# Vectorization

## Prerequisites

* Basics of python programming

## Learning Objective

* Discuss the meaning and need of Vectorization.

* Describe the bag of words model and implement it using sklearn.

* Describe the tfi-df model and implement it using sklearn.

## Introduction
In the previous chapters, you learned about text cleaning, tokenization, and normalization. As a result of all these steps, now you have a list of clean and normalized text documents. This list of the text document is also known as *corpus*. **A corpus is nothing but a list of all the text documents present in a dataset.** But machine learning models cannot work on text data directly. You will need to convert these data into numerical values. There are many ways to extract numerical features from text data. In this section, you will learn about the two most popular ways to extract features from text data:

* Bag of Words Model

* TFIDF Model

## Bag of Words model

The bag of words model is a simple yet effective way to extract features from text data.

For example, consider that a dataset consists of two reviews of some movie:  

**review 1**: *good movie but bad script.*  

**review 2**: *action was good but movie was bad.*

The first step would be to find the list of **unique** words present in the dataset. This list is called the **vocabulary** of the data. Then each word from the vocabulary is treated as a feature. By doing so, each review can now be represented by the number of times each word from the vocabulary appears in the review. The Bag of Words model represents the above two reviews as:

<div align="center">
    <figure>
        <!-- <img src="https://drive.google.com/uc?export=view&id=1OHYiTEf-pcYnr5YL5PVfXsJqVH5FYSwg"> -->
        <img src="https://i.postimg.cc/k5npMNDF/image.png">
        <figcaption>Fig. Feature matrix created using Bag of Words Model</figcaption>
    </figure>
</div>

This approach is called bag of words because it **only cares about the words that appear in the dataset, not their order**. Exactly the way you stuff things in a bag.

Let's illustrate this using the same movie review example from above. There are two reviews *i.e.,* two text documents. Let's manually create a list `corpus` containing two reviews.

In [1]:
review_1 = "good movie but bad script"
review_2 = "action was good but movie was bad."

Now let's create a corpus containing both the reviews.

In [2]:
corpus = [review_1, review_2]

You can use the [`CountVectorizer`](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html) from `sklearn` to create a feature matrix of a given text dataset. Using `CountVectorizer` is similar to using other methods from sklearn. First you instantiate the `CountVectorizer` class. Then you `fit_transform` the data's corpus to transform it into a feature matrix.

In [3]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
type(X)

scipy.sparse._csr.csr_matrix

The `fit_transform` method returns a sparse matrix. To convert into a normal matrix, you can use the `.toarray()` method. Let's use the pandas dataframe to visualize the feature matrix of our two reviews.

In [ ]:
import pandas as pd
pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names())

## TF-IDF Model

**Term frequency-inverse document frequency(tf-idf)** is a technique to quantify a word's importance in documents. It is the product of two statistics: **Term Frequency** and **Inverse Document Frequency**. Let's look at each of them in detail.

### Term Frequency $(tf)$

A term frequency for a word/term in a document is the number of times the particular term occurs in the document divided by the total number of words in that document. *i.e.*

$$tf\text{ of a word in a doc} = \frac{\text{No. of times the word occurs in the doc}}{\text{Total no. of words in the doc}}$$

\\

If you denote the number of times a particular word $i$ occurs in a document $j$ as $f_{i,j}$ and the total number of words in the document $j$ as $n_j$ then term frequency of the word $i$ in document $j$ is given by:

$$tf({i,j}) = \frac {f_{i, j}} {n_{j}}$$


As expected, the term frequency of a word increases if the word frequently occurs in the document.

Let's understand term frequency with an example. Consider the first review from the earlier example *i.e.* *good movie but bad script*. Here, the word $i$ is *good* and the document $j$ is the review *good movie but bad script*. The word *good* appears only once in the review so $f_{i, j} = 1$ and the total number of words in the review is $n_j=5$. So you can calculate the term frequency of the word *good* in the review easily as:

$$tf({i,j}) = \frac {1} {5} = 0.2$$

Similarly, you can calculate the $tf$ of each word in each of the reviews.

### Inverse Document Frequency $(idf)$

Inverse Document Frequency of a word measures how common or rare the word is **across all the documents**. It is the log of the total number of documents divided by the number of documents containing that particular word. *i.e.*

$$
idf\text{ of a word} = log \bigg(\frac{\text{total number of documents}}{\text{number of document with term i in it}}\bigg)
$$

\

If you denote the total number of documents by $N$ and the number of documents containing a particular word $i$ by $c_i$ then the $idf$ of the word is given by:

$$
idf(i) = log\bigg(\frac {N} {c_i}\bigg)
$$

The fraction $\frac {N} {c_i}$ can take significantly larger values specially when a word is rare and the number of documents is large. The $log$ is used to prevent the $idf$ from dominating the $tf$-$idf$ score.

However, we don't use the $log$ in $tf$ because $tf$ cannot take significantly large values like $idf$ as it is already normalized by the total number of words in the document.

\

The $idf$ of the words which are rare across all the documents is higher than the common ones. This makes sense as the words common across all the documents may not provide any defining information about a particular document.

Let's understand $idf$ with the same movie review example. There are $N=2$ documents:

1. *good movie but bad script.*

2. *action was good but movie was bad.*


Suppose that you wanted to calculate the $idf$ of the word $i=good$. Both the documents contain the word *good* *i.e.* $c_i=2$. So you can calculate the term frequency of the word *good* as:

$$idf(i) = log\bigg(\frac {2} {2}\bigg) = 0$$

As expected, the word *good* is common across both the documents. So it has a low $idf$.

Similarly the $idf$ of the word *script* is $log\big(\frac{2}{1}\big) = 0.301$ which is larger than that of the word *good* because it appears only in one document.

### tf-idf

Finally, the tf-idf for a particular word $i$ in a document $j$ is calculated as the product of its $tf$ in the document $j$ and its $idf$. *i.e.*

$$tf \text{-} idf(i,j) = tf(i,j) \times idf(i)$$

The $tf\text{-}idf$ of the word *good* in the first review is $0.2 \times 0 = 0$. The word *good* in the first review will now be represented using its $tf\text{-}idf$ *i.e.* $0$. Other words in the documents are represented similarly. One thing to note here is that the $tf$ of a word may change in each document, but its $idf$ remains the same across all the documents.

You can use the [`TfidfVectorizer`](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html) class from `sklearn` to create a feature matrix of a given text dataset. Using `TfidfVectorizer` is similar to using `CountVectorizer`. First, you instantiate the `TfidfVectorizer` class. Then you `fit_transform` the data's corpus to transform it into a feature matrix. Let's use the same corpus defined above containing two movie reviews.

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)
pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names())

     action       bad       but      good     movie    script       was
0  0.000000  0.409090  0.409090  0.409090  0.409090  0.574962  0.000000
1  0.377292  0.268446  0.268446  0.268446  0.268446  0.000000  0.754584

**Note:** `sklearn` uses additional smoothing for the log function due to which the $tf\text{-}idf$ values that sklearn computed is different than the ones calculated manually.

## Vectorizing a Real World Dataset

Now that you know what vectorization is and why it is necessary, let's implement it on a real world dataset. You will use the same [SMS Spam Collection](https://archive.ics.uci.edu/ml/datasets/SMS+Spam+Collection) dataset that you had used in the earlier chapters.

In [ ]:
import pandas as pd
dataset = pd.read_csv('https://storage.googleapis.com/codehub-data/1-lv1-7-1-spam.tsv', sep='\t', names=['spam', 'sms'])
dataset.head()

   spam                                                sms
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

Let's first quickly define the `clean_text` and `normalize_text` function from the previous chapters as you will require them here as well before vectorization.

In [ ]:
# Text Cleaning

def clean_text(string):

    import re
    from bs4 import BeautifulSoup

    # Removing URLs
    string = re.sub("http\S+", " ", string)

    # Removing html tags
    string = BeautifulSoup(string, 'lxml')
    string = string.get_text()

    # Decontraction
    string = re.sub(r"n\'t", " not", string)
    string = re.sub(r"\'re", " are", string)
    string = re.sub(r"\'s", " is", string)
    string = re.sub(r"\'d", " would", string)
    string = re.sub(r"\'ll", " will", string)
    string = re.sub(r"\'t", " not", string)
    string = re.sub(r"\'ve", " have", string)
    string = re.sub(r"\'m", " am", string)

    # Removing Punctuations and numbers
    string = re.sub('[^A-Za-z]+', ' ', string)

    return string

In [ ]:
# Text Normalization

def normalize_text(tokens):

    from nltk.stem import PorterStemmer

    # lowercasing all the tokens
    tokens = [token.lower() for token in tokens]

    # stemming all the tokens
    stemmer = PorterStemmer()
    tokens = [stemmer.stem(token) for token in tokens]

    return tokens

tokens = normalize_text(['Formulated', 'and', 'formulating', 'are', 'the', 'two', 'tenses', 'of', 'Formulate'])
print(tokens)

['formul', 'and', 'formul', 'are', 'the', 'two', 'tens', 'of', 'formul']

You'll also need the `word_tokenize` function from `nltk` to tokenize the messages before vectorization.

In [ ]:
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

Let's first clean, tokenize, normalize, and remove stopwords from the text documents. This is exactly the same code from the previous chapter.

In [ ]:
nltk.download('stopwords')
from nltk.corpus import stopwords
eng_stopwords = stopwords.words('english')

corpus = [] # list containing all the preprocessed messages in dataset

# for each message in the document.
for message in dataset['sms']:

  # cleaning the message
  message = clean_text(message)

  # tokenizing the message
  tokens = word_tokenize(message)

  # text normalization
  tokens = normalize_text(tokens)

  # stopwords removal
  tokens = [token for token in tokens if token not in eng_stopwords]

  # getting back the original text
  string = " ".join(tokens)

  corpus.append(string)

for document in corpus[:10]:
  print(document)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
go jurong point crazi avail onli bugi n great world la e buffet cine got amor wat
ok lar joke wif u oni
free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli
u dun say earli hor u c alreadi say
nah think goe usf live around though
freemsg hey darl week word back would like fun still tb ok xxx std chg send rcv
even brother like speak treat like aid patent
per request mell mell oru minnaminungint nurungu vettam ha set callertun caller press copi friend callertun
winner valu network custom select receivea prize reward claim call claim code kl valid hour onli
mobil month u r entitl updat latest colour mobil camera free call mobil updat co free

The list `corpus` contains all the messages in the dataset in their cleaned and normalized form. You can also see that none of the messages contain the stopwords. Now you will use the `CountVectorizer` from sklearn to transform this list of documents into a feature matrix using the bag of words model. Here, you instantiate it with the maximum number of features you want in your feature matrix, in our case, 500. This will select the top 3000 most frequent words from the messages to be the features.

In [ ]:
vectorizer = CountVectorizer(max_features=500)
X = vectorizer.fit_transform(corpus)
pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names())

      abl  abt  account  actual  address  ...  yesterday  yet  yo  yr  yup
0       0    0        0       0        0  ...          0    0   0   0    0
1       0    0        0       0        0  ...          0    0   0   0    0
2       0    0        0       0        0  ...          0    0   0   0    0
3       0    0        0       0        0  ...          0    0   0   0    0
4       0    0        0       0        0  ...          0    0   0   0    0
...   ...  ...      ...     ...      ...  ...        ...  ...  ..  ..  ...
5567    0    0        0       0        0  ...          0    0   0   0    0
5568    0    0        0       0        0  ...          0    0   0   0    0
5569    0    0        0       0        0  ...          0    0   0   0    0
5570    0    0        0       0        0  ...          0    0   0   0    0
5571    0    0        0       0        0  ...          0    0   0   0    0

[5572 rows x 500 columns]

As you can see, the `corpus` has been transformed into a feature matrix using the bag of words model. You can now fit machine learning models to this feature matrix. In the next unit, you will fit the Naive Bayes model on this feature matrix.

## Key Takeaways

* Vectorization is the process of converting text data into a numerical one.

* Bag of Words model represents a text data using the frequency of words present in it.

* You can use CountVectorization from sklearn to implement bag of words model

* tfi-df model uses the frequency of the words along with their importance to represent the text data.

* You can use TfidfVectorization from sklearn to implement tfidf model